### ISSUE TITLE
npm publish access

### ISSUE THREAD

**Issue by joshjordan** [supervillain-software-group/axios-rest-resource#45]
Hello @aigoncharov thanks for granting maintainer access on the repo. We're going to push it forward! I just merged a bunch of dependabot PRs and I'd like to release a new version to npm.

Could you add me as an owner? To keep this short and sweet for you, I've written the command I think you need:

```
npm owner add joshjordan axios-rest-resource
```

Optionally (your decision): 

```
npm owner rm aigoncharov axios-rest-resource
```

**Comment by fxlrnrpt** [comment]
Sent the invite!

**Comment by fxlrnrpt** [comment]
@joshjordan could you check if you have the full access and can push? I'll remove myself from the package then

**Comment by joshjordan** [comment]
@aigoncharov 0.4.2 published successfully :)

**Comment by fxlrnrpt** [comment]
@joshjordan removed myself. All yours now :)

**Comment by joshjordan** [comment]
Cheers my friend. Thanks!
